services:
  roll-service:
    build: main
    expose:
      - "5000:5000"
  user-service:
    build: service2
    expose:
      - "5001:5001"
  user-service-copy:
    build: service3
    expose:
      - "5003:5003"
  req-service:
    build: req_service
    restart: "on-failure:5"
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.8.0
    ports:
      - "16686:16686"  # UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
      - "5778:5778"    # Configuration
      - "9411:9411"    # Zipkin
