version: '3.8'

services:
  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.56
    container_name: jaeger-agent
    ports:
      - "5775:5775/udp"    # UDP для tchannel
      - "6831:6831/udp"    # UDP для UDP-Thrift (used by most clients)
      - "6832:6832/udp"    # UDP для UDP-compact Thrift
      - "5778:5778"        # HTTP для получения конфигурации
    command:
      - "--reporter.grpc.host-port=jaeger-collector:14250"
    depends_on:
      - jaeger-collector

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.56
    container_name: jaeger-collector
    ports:
      - "14267:14267"      # HTTP для приема данных (Thrift)
      - "14268:14268"      # HTTP для приема данных (JSON)
      - "14250:14250"      # gRPC-приемник от агента
      - "9411:9411"        # Zipkin совместимость
    environment:
      - SPAN_STORAGE_TYPE=memory

  jaeger-query:
    image: jaegertracing/jaeger-query:1.56
    container_name: jaeger-query
    ports:
      - "16686:16686"      # Веб-интерфейс Jaeger
    environment:
      - SPAN_STORAGE_TYPE=memory
    depends_on:
      - jaeger-collector
